Fixed ratemyprofessor link
ComputerScienceHouse/schedulemaker pull request #334
Opened 2023-11-19 03:32 UTC by esoccoli

2023-11-20 20:34 UTC, Mstrodl requested changes

2023-11-20 20:34 UTC, Mstrodl commented on api/rmp.php
> +curl_setopt($curl, CURLOPT_URL, "http://www.ratemyprofessors.com/SelectTeacher.jsp?searchName= . $name . "&search_submit1=Search&sid=807");
I really don't think this does what you think it does

2023-11-27 18:04 UTC, jabbate19 commented
Fixes #324

2023-11-27 20:53 UTC, nsp7786 commented
Based on #324 , you'd want a link like this: `https://www.ratemyprofessors.com/search/professors?q=${name}&sid=${schoolId}` (RIT's school id is `U2Nob29sLTgwNw==`)

2023-12-26 20:26 UTC, MoralCode commented
As the author of #324 and based on the line under review above, it looks like the line should be
`curl_setopt($curl, CURLOPT_URL, "https://www.ratemyprofessors.com/search/professors?q=" . $name . "&sid=U2Nob29sLTgwNw==");`

Would be awesome to see this get fixed in ScheduleMaker!

2024-01-03 04:28 UTC, Mstrodl commented
Obsolete, and wasn't the right file anyways.

2024-01-03 04:28 UTC, closed without merging

2024-01-03 05:24 UTC, MoralCode commented
ah cool, thanks for fixing this! (commit: https://github.com/ComputerScienceHouse/schedulemaker/commit/77ad61b183ad700c95f511cf96d6954af89b478c for anyone looking to see how it was done)

If this indeed "wasn't the right file anyways", then it seems as though the core issue (#324) is still not resolved