Update Schedule.php to fix iCal's that have classes that happen on multiple days of the week
ComputerScienceHouse/schedulemaker pull request #339
Opened 2023-12-26 20:18 UTC by natep-tech

## Updated the `generateIcal()` function. (Breaking out the multiple changes from #325 into separate PRs for clarity)

Added code that'll generate a single series for a multi-day course (Mon,Web,Fri for example) to simplify calendars (see the [iCal specification for RRULE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)). If any details are different between the different times (different location or times, for example) it'll fallback to the old code that makes separate series for each listed time in the course. #63

2024-01-03 05:01 UTC, Mstrodl commented
Please fix merge conflicts

2024-01-03 06:45 UTC, natep-tech commented
Merge conflicts should be resolved now.

2024-01-08 17:31 UTC, natep-tech commented
I ran a rebase again, hopefully that fixes everything

2024-01-08 21:30 UTC, Mstrodl requested changes
I'm going to see if I can fix this

2024-01-08 21:30 UTC, Mstrodl commented on api/src/Schedule.php
> +    }
Looks like this hunk was added by mistake?

2024-01-08 21:30 UTC, Mstrodl commented on api/src/Schedule.php
> +                //if the details for the course are equal across each day, then set up a series that repeats on each day the course runs
This doesn't handle a class with Monday/Wednesday in room A and Friday in room B.

2024-01-08 23:57 UTC, natep-tech commented on api/src/Schedule.php
> +    }
You are correct, this will be resolved by the next commit.

2024-01-08 23:57 UTC, natep-tech commented on api/src/Schedule.php
> +                //if the details for the course are equal across each day, then set up a series that repeats on each day the course runs
The merge seems to have left strands of code in the wrong locations - I'll fix this in the next commit.

2024-01-09 00:01 UTC, natep-tech commented
I apologize about the trouble with this PR. Thank you for your patience, the twp comments you left should have been resolved by my latest commit. 

I'm doing another quality review tonight to ensure the rest of the file is up to snuff.

2024-01-09 02:41 UTC, Mstrodl commented
superseded by #343

2024-01-09 02:41 UTC, closed without merging